version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - aerospike
      - redis
    environment:
      NODE_ENV: production
      APP_HOST: http://10.61.40.181
      APP_PORT: 4000
      AEROSPIKE_HOST: aerospike
      AEROSPIKE_PORT: 3000
      AEROSPIKE_NAMESPACE: logroom
      REDIS_PORT: 6379
      REDIS_HOST: redis

  aerospike:
    image: aerospike/aerospike-server:latest
    volumes: 
      - ./aerospike/etc:/opt/aerospike/etc
    command: asd --foreground --config-file /opt/aerospike/etc/aerospike.conf

  redis:
    image: redis:latest