const SOCKET_F_START_LISTEN_SESSION = 'SOCKET_F_START_LISTEN_SESSION';
const SOCKET_F_STOP_LISTEN_SESSION = 'SOCKET_F_STOP_LISTEN_SESSION';
const SOCKET_B_PUSH_LOGS = 'SOCKET_B_PUSH_LOGS';
const SOCKET_B_STOP_LISTEN_SESSION_SUCCESS = 'SOCKET_B_STOP_LISTEN_SESSION_SUCCESS';
const SOCKET_B_NEW_ACTIVE_SESSION = 'SOCKET_B_NEW_ACTIVE_SESSION';
const SOCKET_B_ACTIVE_SESSION_UPDATED = 'SOCKET_B_ACTIVE_SESSION_UPDATED';

module.exports = {
  SOCKET_F_START_LISTEN_SESSION,
  SOCKET_F_STOP_LISTEN_SESSION,
  SOCKET_B_PUSH_LOGS,
  SOCKET_B_STOP_LISTEN_SESSION_SUCCESS,
  SOCKET_B_NEW_ACTIVE_SESSION,
  SOCKET_B_ACTIVE_SESSION_UPDATED,
};
