const SOCKET_F_START_LISTEN_SESSION = 'SOCKET_F_START_LISTEN_SESSION';
const SOCKET_F_STOP_LISTEN_SESSION = 'SOCKET_F_STOP_LISTEN_SESSION';
const SOCKET_B_PUSH_LOGS = 'SOCKET_B_PUSH_LOGS';

module.exports = {
  SOCKET_F_START_LISTEN_SESSION,
  SOCKET_F_STOP_LISTEN_SESSION,
  SOCKET_B_PUSH_LOGS
};
